id: P007873
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG08457
  title: དུང་དཀར་བློ་བཟང་འཕྲིན་ལས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    8fbdf27445094ca9b903f63e4a7be728:
      image_group_id: I1KG564
      title: ''
      volume_number: 1
      total_pages: 646
ebook_metadata:
  title: དུང་དཀར་བློ་བཟང་འཕྲིན་ལས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007873
  cover: cover.jpg
  layers:
  - pagination
