id: P007873
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:29.609010
source_metadata:
  id: bdr:W00KG08457
  title: དུང་དཀར་བློ་བཟང་འཕྲིན་ལས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    d95d7f7534704613966a4ec083aab2b9:
      image_group_id: I1KG564
      title: Volume 1 of gsung rtsom/_blo bzang 'phrin las
      volume_number: 1
      total_pages: 646
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
