id: I5B2526E5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:10:43+00:00'
last_modified: '2022-06-09T06:53:28.918700+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG08457
  title: དུང་དཀར་བློ་བཟང་འཕྲིན་ལས་ཀྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    3C1B:
      image_group_id: I1KG564
      title: Volume 1 of gsung rtsom/_blo bzang 'phrin las
      total_pages: 646
      order: 1
      base_file: 3C1B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
